language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=""  WITH_COVERAGE=1 # environment to test with the latest version of NumPy
  - NUMPY_VERSION="=1.8"
  - NUMPY_VERSION="=1.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy${NUMPY_VERSION} scipy matplotlib openpyxl=1.8.2 pandas nose
  - source activate env_name
  - pip install sphinx sphinx-bootstrap-theme coverage coveralls
  - pip install -e .
script:
  - flake8 emperor/*.py tests/*.py scripts/*.py setup.py
  # execute the full test suite
  - python tests/all_tests.py --emperor_scripts_dir scripts
  # we just check coverage in the latest version of NumPy
  - if [ ${WITH_COVERAGE} ]; then nosetests emperor --with-coverage --cover-package=emperor --cover-inclusive tests; fi
  - make -C doc html
after_success:
  - coveralls
